esphome:
  name: eps-power-ctrl02
  friendly_name: EPS_POWER_CTRL02

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CFhviDLEri+8e7Z8Cbqb2AS3B0nZr0n4Pyiv+SlXQUg="

ota:
  - platform: esphome
    password: "4d49797021721ce5f9f0d423abbca246"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eps-Power-Ctrl02"
    password: "ISNbUQNYZBbm"

switch:
  #开关控制
  - platform: gpio
    pin: GPIO4
    id: IO_PowerControl
    name: "ON/OFF"
    #inverted: true
    restore_mode: ALWAYS_ON  # 默认上电开启

binary_sensor:
  - platform: gpio
    name: "HumanDetect"
    pin: GPIO3



captive_portal:
    